### ISSUE TITLE
Mocha userstyle page directs to frappé; no obvious way to install mocha variant.

### ISSUE THREAD

**Issue by Sourcastic** [catppuccin/wikiwand#3]
The mocha link links to a userstyle page for mocha, but installing it actually installs frappé via the stylus extension. Would be a really good thing to fix, seeing how there's no obvious way to install mocha currently. Unless it's a mistake in my end of course :p

**Comment by coldenate** [comment]
I also have this issue :).
#2 does a great job at explaining it
